import Navbar from "@/components/landing/Navbar";
import { Analytics } from "@vercel/analytics/next";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  // weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
// const poppins = Poppins({
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// });

export const metadata: Metadata = {
  title: "Academy | WonderHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased scrollbar-hide`}>
      <Analytics />
      <body
        className={`${montserrat.className} font-medium w-screen overflow-x-hidden relative`}
      >
        <div className="fixed bg-pink-200 z-0 rounded-full -top-120 sm:-top-100 w-200 h-200 -left-120 sm:-left-100" />
        <div className="relative inset-0 z-50 backdrop-blur-3xl">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
