import { QueryProvider } from "@/components/global/QueryProvider";
import { Analytics } from "@vercel/analytics/next";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const montserrat = Montserrat({
  // weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
// const poppins = Poppins({
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// });

export const metadata: Metadata = {
  title: "Academy | WonderHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased scrollbar-hide`}>
      <Analytics />
      <QueryProvider>
        <body
          className={`${montserrat.className} font-medium w-screen overflow-x-hidden relative`}
        >
          <Toaster
            position="top-center"
            toastOptions={{
              style: {
                borderRadius: "10px",
                fontSize: 14,
              },
            }}
          />
          <div className="fixed bg-pink-200 z-0 rounded-full -top-120 sm:-top-100 w-200 h-200 -left-120 sm:-left-100" />
          <div className="backdrop-blur-3xl min-h-screen">{children}</div>
        </body>
      </QueryProvider>
    </html>
  );
}
